[project]
name = "kssb-menu"
version = "0.1.0"
description = "Scrape the menus of the Kansas State School for the Blind"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.5",
]
